# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: df.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='df.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x64\x66.proto\"\x07\n\x05\x45mpty\"\x19\n\x05\x44\x46Row\x12\x10\n\x08row_data\x18\x01 \x01(\t\"\x1b\n\x07\x42yteRow\x12\x10\n\x08row_data\x18\x01 \x01(\x0c\x32\xba\x03\n\x10\x44\x61taFrameService\x12\x1f\n\x0bGetDFbyJSON\x12\x06.Empty\x1a\x06.DFRow0\x01\x12 \n\x0cGetDFbyuJSON\x12\x06.Empty\x1a\x06.DFRow0\x01\x12!\n\rGetDFbyorJSON\x12\x06.Empty\x1a\x06.DFRow0\x01\x12\x1e\n\nGetDFbyCSV\x12\x06.Empty\x1a\x06.DFRow0\x01\x12 \n\x0cGetDFbydtCSV\x12\x06.Empty\x1a\x06.DFRow0\x01\x12 \n\nGetDFbyJAY\x12\x06.Empty\x1a\x08.ByteRow0\x01\x12\"\n\x0eGetChunkedJSON\x12\x06.Empty\x1a\x06.DFRow0\x01\x12#\n\x0fGetChunkeduJSON\x12\x06.Empty\x1a\x06.DFRow0\x01\x12$\n\x10GetChunkedorJSON\x12\x06.Empty\x1a\x06.DFRow0\x01\x12!\n\rGetChunkedCSV\x12\x06.Empty\x1a\x06.DFRow0\x01\x12#\n\x0fGetChunkeddtCSV\x12\x06.Empty\x1a\x06.DFRow0\x01\x12%\n\x11GetChunkedFeather\x12\x06.Empty\x1a\x06.DFRow0\x01\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=19,
)


_DFROW = _descriptor.Descriptor(
  name='DFRow',
  full_name='DFRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_data', full_name='DFRow.row_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=46,
)


_BYTEROW = _descriptor.Descriptor(
  name='ByteRow',
  full_name='ByteRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_data', full_name='ByteRow.row_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['DFRow'] = _DFROW
DESCRIPTOR.message_types_by_name['ByteRow'] = _BYTEROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'df_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

DFRow = _reflection.GeneratedProtocolMessageType('DFRow', (_message.Message,), {
  'DESCRIPTOR' : _DFROW,
  '__module__' : 'df_pb2'
  # @@protoc_insertion_point(class_scope:DFRow)
  })
_sym_db.RegisterMessage(DFRow)

ByteRow = _reflection.GeneratedProtocolMessageType('ByteRow', (_message.Message,), {
  'DESCRIPTOR' : _BYTEROW,
  '__module__' : 'df_pb2'
  # @@protoc_insertion_point(class_scope:ByteRow)
  })
_sym_db.RegisterMessage(ByteRow)



_DATAFRAMESERVICE = _descriptor.ServiceDescriptor(
  name='DataFrameService',
  full_name='DataFrameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDFbyJSON',
    full_name='DataFrameService.GetDFbyJSON',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDFbyuJSON',
    full_name='DataFrameService.GetDFbyuJSON',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDFbyorJSON',
    full_name='DataFrameService.GetDFbyorJSON',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDFbyCSV',
    full_name='DataFrameService.GetDFbyCSV',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDFbydtCSV',
    full_name='DataFrameService.GetDFbydtCSV',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDFbyJAY',
    full_name='DataFrameService.GetDFbyJAY',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_BYTEROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkedJSON',
    full_name='DataFrameService.GetChunkedJSON',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkeduJSON',
    full_name='DataFrameService.GetChunkeduJSON',
    index=7,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkedorJSON',
    full_name='DataFrameService.GetChunkedorJSON',
    index=8,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkedCSV',
    full_name='DataFrameService.GetChunkedCSV',
    index=9,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkeddtCSV',
    full_name='DataFrameService.GetChunkeddtCSV',
    index=10,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkedFeather',
    full_name='DataFrameService.GetChunkedFeather',
    index=11,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DFROW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAFRAMESERVICE)

DESCRIPTOR.services_by_name['DataFrameService'] = _DATAFRAMESERVICE

# @@protoc_insertion_point(module_scope)
